### ISSUE TITLE
Drop-down menu problems on 

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#22]
I cannot click on any of the "Drop--down" options, e.g. "Research interests". (Try it! Maybe the font needs to be reduced, there's some overflow onto the next line?)

**Comment by siddhartha-gadgil** [comment]
I don't see "Research interests". Where do you get this problem - on phones?

**Comment by apukhare** [comment]
Perhaps not major.

**Comment by siddhartha-gadgil** [comment]
We should try to fix this, but I don't know that much html. I read stuff
about z-index
