### ISSUE TITLE
Update member directory

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#23]
E.g. Kalaivani is listed on the postdoc page, but (Venkatesh tells me) she has left IISc by now.

The recent additions are not included either. We may want to get help with this too. (Student list as well as postdoc list.)

**Comment by siddhartha-gadgil** [comment]
Entered names etc for 2017 students, all postdocs. Should

* Enter their user-ids
* Check e-mail of Mrs. Roopa
* Check which postdocs etc have left. (also students who have graduated)

**Comment by siddhartha-gadgil** [comment]
Blank e-mails now, so no longer blocking

**Comment by siddhartha-gadgil** [comment]
Only regular maintainence - removing those who have left, remains.
