### ISSUE TITLE
Faculty page - now-vestigial commas after names

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#24]
Now that "Ph.D." is moved inside parentheses, there need not be a comma after each faculty's name. The same might apply to postdocs in the future.

I tried to change it in "faculty.yaml" but I think it's to be done in the layout, not the data set, so please can you make the change? Thank you!

**Comment by siddhartha-gadgil** [comment]
Done it. It is in the page "faculty.html"
