### ISSUE TITLE
Faculty PhD page - minor typos

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#25]
**1.** Harish's PhD says "Strony Brook".
**2.** If Srikant's is "UC, Santa Barbara" then Manju's should also be "UC, Berkeley" for consistency. Or vice versa. (You see, you may regret inviting me to edit! :) )
**3.** Pooja's and Venkatesh's PhD-affiliations need to be made consistent.
**4.** We are missing Vamsi's phone number. (I'll email him and you.)

**Comment by siddhartha-gadgil** [comment]
Will you fix this in faculty.yaml

**Comment by apukhare** [comment]
Done.
