### ISSUE TITLE
List of small edits remaining, on PhD/IntPhD etc. webpages

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#27]
**1.** Do the photos match the postdocs? Are the postdoc/student lists correct? (Get Head Office to provide current lists first?) Also, some PhD students do not have photographs. Ideally, we ought to include the offices of the PhD students on the webpage (so that UGs can benefit). I also think it might be nice to include the names of the mathematics majors (the UGs) but this is debatable. Such a venture can be automated I think.

**2.** Should we email "all" to check lists etc. for up-to-date-ness, giving them a deadline of e.g. Monday to respond. (This would be after Faculty approves the transfer tomorrow, hopefully, and before we make the transfer.)

**3.** The (https://siddhartha-gadgil.github.io/DeptWeb/degprog-intphd Int-PhD webpage) has 2016 listed all over it.

**4.** In the (https://siddhartha-gadgil.github.io/DeptWeb/degprog-phd.html PhD webpage),
(a) The first line says "Visit this_page" - but there is no hyperlink here. (THIS IS GAUTAM-SPEAK FOR ``THIS PARTICULAR WEBPAGE YOU ARE ON)

(b) I think we should change "Career in Mathematics" to "Careers..." - I certainly hope there isn't just one career! (DONE)

(c) Towards the bottom, the links to the Question Papers / Answer Keys doesn't work - I assume that will be fixed once it is imported to the actual website?

**5.** The (https://siddhartha-gadgil.github.io/DeptWeb/pros-fac.html Prospective Faculty webpage) needs to be updated from 2013 data, especially since the 7th Pay Commission is in place (even if we are to be post-paid?). (THIS IS COMPLICATED. THE 7TH PAY COMMISSION IS A MYTH (IN MY HIGHLY CONCEITED OPINION).)

**6.** The footer includes a postal address, but no phone number - is this deliberate? If not, maybe include +91-80-... ? Also, should the footer have a ``last updated on so and so"? (I THINK THE PHONE NUMBER CAN BE FOUND IN THE ``CONTACT" SECTION ANYWAY.)

**7.**  Include designations of faculty in the faculty page ?

**8.** Descriptions of research areas need to be filled in.

**9.**  In the Courses page, I think we should have separate links for ``official syllabus" and ``current webpage" or something like that.

**10.** In ``contact us", should we post a google map from the main gate to the department ?

**11.** In the publications webpage, can we get that ``by year" part on the top instead of the bottom ?

**12.** We should (like Stony Brook) have a login for faculty where they can view past qualifying exams, past course webpages, email aliases, recruitment data, etc. This is a long-term thing. Not urgent of course.

**13.** The webpages of the faculty seem to have a separate field devoted to them. Is this a feature or a bug ? I mean, we could simply make their names hyperlinks can we not ?

**Comment by siddhartha-gadgil** [comment]
* 2 - I was thinking of a waiting period of say a week before making the transfer (if approved). Can have selected files in a shared Dropbox folder as well as respond to e-mails in this time.
* 3, 4(a), 4(b) should be fixed.
* 4(c) - mysterious - I had fixed it on my desktop this morning, but seem to have created confusion with git. Will repair.
* 6 - footer is just a `placeholder' for me to experiment with appearance. Please edit the content.
* 7- for discussion
* 9 - in the long run , yes.
* 10 - Very good idea
* 11 - I'll work on this.
* 12 - in the long run, but this is a separate kind of issue (involving authentication). Perhaps the new IISc system will allow this.
* 13 - Good idea - made the name clickable  and removed the webpage entry.

**Comment by vamsipritham** [comment]
One more issue - The Undergraduate Programme link on index.html leads to https://siddhartha-gadgil.github.io/DeptWeb/www.iisc.ernet.in/ug 

I wonder how the index.html by default prefixes links with {{ site.baseurl }}

**Comment by vamsipritham** [comment]
Also on the staff webpage, Mahalakshmi's name seems to be listed. We have to change that to whatchamacallit's name sitting at her desk (I think it is Roopa).

Manju had a suggestion that we ought to have a list of PhD alumni, their advisers, and where they are currently. I think on the PhD students' page, we can also have a field for listing their advisers.

**Comment by siddhartha-gadgil** [comment]
There is a list of all phds as https://siddhartha-gadgil.github.io/DeptWeb/phds.html, but somehow the link to it got lost. Can one of you link it from somewhere (may be research)

**Comment by siddhartha-gadgil** [comment]
Many of these issues have been addressed or won't be, so I am closing this and opening #39
