### ISSUE TITLE
Remaining list of small edits

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/DeptWeb#39]
To streamline workflow, here are surviving issue from #27 except those spawned as #16 and #26  

6. The footer includes a postal address, but no phone number - is this deliberate? If not, maybe include +91-80-... ? Also, should the footer have a last updated on so and so"? (I THINK THE PHONE NUMBER CAN BE FOUND IN THECONTACT" SECTION ANYWAY.)

9. In the Courses page, I think we should have separate links for official syllabus" andcurrent webpage" or something like that.

**Comment by siddhartha-gadgil** [comment]
@apukhare should these two points remain open (there is a catalogue and current courses now, and phone number is on contact)?

**Comment by vamsipritham** [comment]
Actually, I made point 7). So we can remove that.

**Comment by siddhartha-gadgil** [comment]
All that remains is (6) - do we want a phone number. This is an aesthetic judgement of clutter versus convenience.

**Comment by vamsipritham** [comment]
Actually, we can just have the phone number and not the ``IISc Bangalore 560012" stuff. The latter is not really that useful.

**Comment by vamsipritham** [comment]
By the way, Harish sent some background image if I remember right. What happened to that thing ?

**Comment by siddhartha-gadgil** [comment]
Given issues of copyright, latency and mobile friendliness, I son't think
it is worth it. Plus the light-grey issues will resurface.
