### ISSUE TITLE
News page - let's start it here

### ISSUE THREAD

**Issue by apukhare** [siddhartha-gadgil/DeptWeb#40]
See my "comment" on this list.

------------------

**1.** (Month?) 2016: Vamsi P. Pingali got the Early Career Research Award from SERB (2016-2019).
**2.** July 2017: Subhojoy Gupta, Apoorva Khare, Vamsi P. Pingali were selected as Infosys Young Investigators in the Mathematics Department.
**3.** July 2017: Gautam Bharali, E.K. Narayanan, Pooja Singla co-organized the IWM at IISc Bangalore.
**4.** (July-November 2017): Arvind Ayyer and Manjunath Krishnapur organized the long program in ICTS Bangalore. [[Do we want to say this for Simons people? Not necessarily here.]]
**5.** August 2018: (This will be pushed down, but for now it is 5) Apoorva Khare will speak at an ICM Satellite Conference in Cusco, Peru.

Please add to - and edit/correct - this list of items where I put in dates which may not be entirely accurate.

**Comment by apukhare** [comment]
How about making a list of news items here, adding to this "thread" for now in some numerical order. Eventually, we can permute according to chronology and add it to the News page in the website. For now I'm adding awards/honours, and international conference invitations.

I've also added conference organization as it promotes outreach ("Broader Impact"). Maybe it can be removed from the list below, but should be added to our "Analysis and Probability Research Group" website's "News" I think, to show Simons and others about us taking up seriously our "social responsibilities".

Let's make this list, as Gautam and I were discussing at lunch yesterday; and then we can decide how much of it / which of the sub-categories we want to put up on our Math website. There will also be other, actual "news", which I don't know and hence haven't included.

And for now, I'm happy with the website (without this list), and fine with it being sent off!

**Comment by siddhartha-gadgil** [comment]
As soon as we have some news items, I'll add links below seminars with excepts from the news pages.

**Comment by siddhartha-gadgil** [comment]
News page created, used for announcements
