### ISSUE TITLE
Simplified `cron` deployment using Sparrow as Jekyll server 

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/DeptWeb#48]
A better way to manage deployment may be to use sparrow as a _jekyll server_. Individual steps have been tested and timed (total time less than a minute), but scripts are not yet written.

## On Sparrow

* A script which (running with cron)
    - pulls from the repository
    - builds with jekyll for deployment
    - creates a __tarball__ (i.e., zips)
    - copies __tarball__ to an appropriate directory, say `zipsite`.
* run in the background an http-server to serve `zipsite` - the `node-js http-server` is installed and I have used it many times.

## On math

A script to:

* Download the tarball from Sparrow
* extract the tarball
* recursively copy to the running site.

## Running and `cron`

* Both Sparrow and `math` will have scripts which can be triggered manually and will also run as cron jobs.
* the script on `math` should be run as root.

**Comment by siddhartha-gadgil** [comment]
* scripts are written and tested a little.
* no chron jobs yet.
* jekyll server running on sparrow.

**Comment by siddhartha-gadgil** [comment]
* Everything tested. The cron job on math, for a deployment every half hour  is:
```
SHELL=/usr/bin/bash
*/2 * * * * /home/gadgil/ziploy.sh /tmp/webpage &>> /tmp/ziploy.log
```
* the `/tmp/webpage` should be replaced by the correct target (default needs correction).
* the cron job on sparrow is:
```
SHELL=/bin/bash
0 * * * * /home/gadgil/code/DeptWeb/mktar.sh &>> /home/gadgil/mktar.log
```

**Comment by ayyer** [comment]
Ziploy is a nice name!

**Comment by siddhartha-gadgil** [comment]
Many attempts have failed. Instead there is simplified deployment from sparrow.
