### ISSUE TITLE
Update Postdocs and INSPIRE fellows webpage

### ISSUE THREAD

**Issue by ayyer** [siddhartha-gadgil/DeptWeb#49]
Lots of names are missing. Some photos are missing. I have told Surenderan and Roopa to coordinate with each other to streamline the process of adding/removing names.

**Comment by siddhartha-gadgil** [comment]
* The names have been updated.
* The code is changed so missing images are not shown as broken, instead the data has to specify that an image is present.
* A form was posted and images submitted to this (18 including students) have been uploaded.
